version: '3'

services:
  app-first:
    build:
      context: .
      args:
        - HOST_UID=${HOST_UID:-1000}
        - HOST_GID=${HOST_GID:-1000}
    volumes:
      - ./app-first:/var/www
    working_dir: /var/www
    command: php -a
    tty: true
    depends_on:
      - queue
    networks:
      - rabbitmq_test

  app-second:
    build:
      context: .
      args:
        - HOST_UID=${HOST_UID:-1000}
        - HOST_GID=${HOST_GID:-1000}
    volumes:
      - ./app-second:/var/www
    working_dir: /var/www
    command: php -a
    tty: true
    depends_on:
      - queue
    networks:
      - rabbitmq_test

  app-service:
    build:
      context: .
      args:
        - HOST_UID=${HOST_UID:-1000}
        - HOST_GID=${HOST_GID:-1000}
    volumes:
      - ./app-service:/var/www
    working_dir: /var/www
    command: php -a
    tty: true
    depends_on:
      - queue
    networks:
      - rabbitmq_test

  queue:
    image: rabbitmq:3-management
    tty: true
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_test
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root


networks:
  rabbitmq_test:
    driver: bridge