# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    routing_key_request: 'request'
    routing_key_response: 'app1'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'

    App\MessageHandler\ResponseMessageHandler:
        tags: [ { name: messenger.message_handler, bus: response.bus } ]
        # prevent handlers from being registered twice (or you can remove
        # the MessageHandlerInterface that autoconfigure uses to find handlers)
        autoconfigure: false

    App\Service\MessageService:
        arguments:
            $requestRoutingKey: '%routing_key_request%'
            $responseRoutingKey: '%routing_key_response%'